.PHONY: clean All

All:
	@echo "----------Building project:[ Genocop - Debug ]----------"
	@cd "Genocop" && "$(MAKE)" -f  "Genocop.mk"
clean:
	@echo "----------Cleaning project:[ Genocop - Debug ]----------"
	@cd "Genocop" && "$(MAKE)" -f  "Genocop.mk" clean
